<?php

namespace App\Services;

class DummyVervalService
{
    /**
     * Get summary statistics for Dashboard.
     */
    public static function getStats(): array
    {
        return [
            'total_usulan'      => 1250,
            'lolos_verval'      => 845,
            'menunggu_survei'   => 285,
            'tidak_lolos'       => 120,
            'total_anggaran'    => 'Rp 25.000.000.000',
            'alokasi_per_unit'  => 'Rp 20.000.000',
            'progress_tahapan'  => [
                'usulan'         => 1250,
                'verval_admin'   => 1130,
                'survei_fisik'   => 845,
                'penetapan_sk'   => 620,
                'pencairan_dana' => 450,
            ],
            'status_counts'     => [
                'ms'        => 845,  // Memenuhi Syarat
                'menunggu'  => 285,  // Menunggu Verifikasi
                'perbaikan' => 75,   // Perbaikan Berkas
                'tms'       => 45,   // Tidak Memenuhi Syarat
            ],
            'kecamatan_stats'   => [
                'Kalisat'   => 180,
                'Sukowono'  => 165,
                'Silo'      => 210,
                'Arjasa'    => 145,
                'Tempurejo' => 195,
                'Tanggul'   => 175,
                'Sumberbaru'=> 180,
            ],
        ];
    }

    /**
     * Get list of dummy BNBA records for Data Verval.
     */
    public static function getVervalData(): array
    {
        return [
            [
                'id'            => 'BSPS-2026-001',
                'nik'           => '3509121508720001',
                'nama_kk'       => 'Ahmad Syafi\'i',
                'umur'          => 48,
                'tanggungan'    => 4,
                'pekerjaan'     => 'Buruh Tani',
                'penghasilan'   => 'Rp 1.200.000 / bln',
                'kecamatan'     => 'Kalisat',
                'desa'          => 'Glagahwero',
                'dusun'         => 'Krajan RT 02 / RW 01',
                'kondisi_atap'  => 'Rangka Bambu Lapuk, Seng Bocor',
                'kondisi_lantai'=> 'Tanah Liat Sebagian Plester Retak',
                'kondisi_dinding'=> 'Gedek / Bambu Anyam Bolong',
                'legalitas_tanah'=> 'Milik Sendiri (Surat Keterangan Desa / SPPT)',
                'skor_kelaikan' => 88,
                'status_verval' => 'Memenuhi Syarat',
                'status_badge'  => 'success',
                'jenis_bantuan' => 'Peningkatan Kualitas (PK)',
                'fasilitator'   => 'Bambang Eko Santoso, S.T.',
                'tgl_verval'    => '2026-08-04',
                'catatan'       => 'Kondisi struktur berbahaya roboh saat musim hujan, prioritas utama program BSPS.',
            ],
            [
                'id'            => 'BSPS-2026-002',
                'nik'           => '3509152204680003',
                'nama_kk'       => 'Siti Maimunah',
                'umur'          => 56,
                'tanggungan'    => 2,
                'pekerjaan'     => 'Penjual Gorengan',
                'penghasilan'   => 'Rp 900.000 / bln',
                'kecamatan'     => 'Sukowono',
                'desa'          => 'Balet Baru',
                'dusun'         => 'Sumbercanting RT 01 / RW 04',
                'kondisi_atap'  => 'Genteng Usang Sebagian Jatuh',
                'kondisi_lantai'=> 'Tanah Kering',
                'kondisi_dinding'=> 'Papan Kayu Bekas & Sebagian Terpal',
                'legalitas_tanah'=> 'Milik Sendiri (Sertifikat Hak Milik)',
                'skor_kelaikan' => 92,
                'status_verval' => 'Memenuhi Syarat',
                'status_badge'  => 'success',
                'jenis_bantuan' => 'Peningkatan Kualitas (PK)',
                'fasilitator'   => 'Nurul Hidayati, S.Ars.',
                'tgl_verval'    => '2026-08-05',
                'catatan'       => 'Lansia hidup bersama 1 cucu. Dinding samping rawan ambruk terhempas angin.',
            ],
            [
                'id'            => 'BSPS-2026-003',
                'nik'           => '3509081109800004',
                'nama_kk'       => 'Sujarno Subandi',
                'umur'          => 44,
                'tanggungan'    => 3,
                'pekerjaan'     => 'Kuli Bangunan',
                'penghasilan'   => 'Rp 1.500.000 / bln',
                'kecamatan'     => 'Silo',
                'desa'          => 'Sempolan',
                'dusun'         => 'Pondok Gede RT 03 / RW 02',
                'kondisi_atap'  => 'Asbes Retak & Bocor Parah',
                'kondisi_lantai'=> 'Semen Halus Rusak',
                'kondisi_dinding'=> 'Batako Tanpa Plester & Retak Lebar',
                'legalitas_tanah'=> 'Milik Sendiri (Girik / Letter C)',
                'skor_kelaikan' => 76,
                'status_verval' => 'Menunggu Survei',
                'status_badge'  => 'warning',
                'jenis_bantuan' => 'Peningkatan Kualitas (PK)',
                'fasilitator'   => 'Rian Pratama, S.T.',
                'tgl_verval'    => '2026-08-06',
                'catatan'       => 'Menunggu verifikasi lapangan tim teknis TFL gelombang 2.',
            ],
            [
                'id'            => 'BSPS-2026-004',
                'nik'           => '3509200812750002',
                'nama_kk'       => 'Hadi Gunawan',
                'umur'          => 51,
                'tanggungan'    => 5,
                'pekerjaan'     => 'Pekebun Kopi',
                'penghasilan'   => 'Rp 1.300.000 / bln',
                'kecamatan'     => 'Arjasa',
                'desa'          => 'Kemuning Lor',
                'dusun'         => 'Krajan Barat RT 04 / RW 03',
                'kondisi_atap'  => 'Seng Karatan & Rangka Lapuk',
                'kondisi_lantai'=> 'Tanah Lembab',
                'kondisi_dinding'=> 'Bambu Anyam Lapuk',
                'legalitas_tanah'=> 'Milik Keluarga Besar (Belum Waris)',
                'skor_kelaikan' => 68,
                'status_verval' => 'Perbaikan Berkas',
                'status_badge'  => 'info',
                'jenis_bantuan' => 'Peningkatan Kualitas (PK)',
                'fasilitator'   => 'Bambang Eko Santoso, S.T.',
                'tgl_verval'    => '2026-08-07',
                'catatan'       => 'Perlu surat pernyataan persetujuan ahli waris atas penggunaan lahan.',
            ],
            [
                'id'            => 'BSPS-2026-005',
                'nik'           => '3509170305880005',
                'nama_kk'       => 'Budi Darmawan',
                'umur'          => 38,
                'tanggungan'    => 3,
                'pekerjaan'     => 'Pegawai Swasta Kontrak',
                'penghasilan'   => 'Rp 3.800.000 / bln',
                'kecamatan'     => 'Tanggul',
                'desa'          => 'Tanggul Kulon',
                'dusun'         => 'Teknologi RT 01 / RW 05',
                'kondisi_atap'  => 'Genteng Karangpilang Sebagian Baik',
                'kondisi_lantai'=> 'Keramik 40x40',
                'kondisi_dinding'=> 'Bata Merah Plester Cat',
                'legalitas_tanah'=> 'Milik Sendiri (SHM)',
                'skor_kelaikan' => 32,
                'status_verval' => 'Tidak Memenuhi Syarat',
                'status_badge'  => 'danger',
                'jenis_bantuan' => '-',
                'fasilitator'   => 'Nurul Hidayati, S.Ars.',
                'tgl_verval'    => '2026-08-08',
                'catatan'       => 'Penghasilan melebihi batas UMK / MBR dan kondisi rumah telah masuk kategori Rumah Layak Huni (RLH).',
            ],
            [
                'id'            => 'BSPS-2026-006',
                'nik'           => '3509141907650001',
                'nama_kk'       => 'Miswanto',
                'umur'          => 61,
                'tanggungan'    => 1,
                'pekerjaan'     => 'Petani Penggarap',
                'penghasilan'   => 'Rp 800.000 / bln',
                'kecamatan'     => 'Tempurejo',
                'desa'          => 'Sanenrejo',
                'dusun'         => 'Wonoasri RT 05 / RW 02',
                'kondisi_atap'  => 'Rumbia & Ijuk Bocor',
                'kondisi_lantai'=> 'Tanah',
                'kondisi_dinding'=> 'Gedek / Bambu',
                'legalitas_tanah'=> 'Milik Sendiri (Surat Hibah Desa)',
                'skor_kelaikan' => 95,
                'status_verval' => 'Memenuhi Syarat',
                'status_badge'  => 'success',
                'jenis_bantuan' => 'Peningkatan Kualitas (PK)',
                'fasilitator'   => 'Rian Pratama, S.T.',
                'tgl_verval'    => '2026-08-08',
                'catatan'       => 'Sangat mendesak. Sanitas dan MCK keluarga belum tersedia.',
            ],
            [
                'id'            => 'BSPS-2026-007',
                'nik'           => '3509232911790002',
                'nama_kk'       => 'Supardi Al-Amin',
                'umur'          => 47,
                'tanggungan'    => 4,
                'pekerjaan'     => 'Buruh Angkut Pasar',
                'penghasilan'   => 'Rp 1.100.000 / bln',
                'kecamatan'     => 'Sumberbaru',
                'desa'          => 'Yosorati',
                'dusun'         => 'Pasar Lama RT 02 / RW 01',
                'kondisi_atap'  => 'Seng Bekas Berkarat',
                'kondisi_lantai'=> 'Tanah Berdebu',
                'kondisi_dinding'=> 'Triplek Lapuk & Papan Bekas',
                'legalitas_tanah'=> 'Milik Sendiri (Akta Jual Beli / AJB)',
                'skor_kelaikan' => 85,
                'status_verval' => 'Memenuhi Syarat',
                'status_badge'  => 'success',
                'jenis_bantuan' => 'Peningkatan Kualitas (PK)',
                'fasilitator'   => 'Bambang Eko Santoso, S.T.',
                'tgl_verval'    => '2026-08-09',
                'catatan'       => 'Dokumen kependudukan lengkap. Keswadayaan kelompok penerima bantuan aktif.',
            ],
            [
                'id'            => 'BSPS-2026-008',
                'nik'           => '3509120401830006',
                'nama_kk'       => 'Kusno Santoso',
                'umur'          => 43,
                'tanggungan'    => 3,
                'pekerjaan'     => 'Tukang Becak',
                'penghasilan'   => 'Rp 950.000 / bln',
                'kecamatan'     => 'Kalisat',
                'desa'          => 'Ajung',
                'dusun'         => 'Gumuk RT 01 / RW 03',
                'kondisi_atap'  => 'Genteng Retak Rangka Melengkung',
                'kondisi_lantai'=> 'Plesteran Semen Rusak Berat',
                'kondisi_dinding'=> 'Bambu Belah',
                'legalitas_tanah'=> 'Milik Sendiri (Letter C No. 412)',
                'skor_kelaikan' => 82,
                'status_verval' => 'Memenuhi Syarat',
                'status_badge'  => 'success',
                'jenis_bantuan' => 'Peningkatan Kualitas (PK)',
                'fasilitator'   => 'Nurul Hidayati, S.Ars.',
                'tgl_verval'    => '2026-08-09',
                'catatan'       => 'Swadaya masyarakat setempat siap membantu tenaga pengerjaan fisik.',
            ],
        ];
    }

    /**
     * Get recent TFL activity logs.
     */
    public static function getRecentActivities(): array
    {
        return [
            [
                'petugas' => 'Nurul Hidayati, S.Ars.',
                'aktivitas'=> 'Verifikasi Lapangan RTLH Desa Balet Baru (Sukowono)',
                'waktu'   => '10 menit yang lalu',
                'status'  => 'Selesai Survei',
                'badge'   => 'success',
            ],
            [
                'petugas' => 'Bambang Eko Santoso, S.T.',
                'aktivitas'=> 'Input Data BNBA Usulan Desa Glagahwero (Kalisat)',
                'waktu'   => '45 menit yang lalu',
                'status'  => 'Lolos Administrasi',
                'badge'   => 'info',
            ],
            [
                'petugas' => 'Rian Pratama, S.T.',
                'aktivitas'=> 'Pemeriksaan Berkas Kepemilikan Tanah Desa Sempolan (Silo)',
                'waktu'   => '2 jam yang lalu',
                'status'  => 'Perlu Perbaikan',
                'badge'   => 'warning',
            ],
            [
                'petugas' => 'Bambang Eko Santoso, S.T.',
                'aktivitas'=> 'Verifikasi Fisik Calon Penerima Bantuan Desa Sanenrejo (Tempurejo)',
                'waktu'   => '4 jam yang lalu',
                'status'  => 'Selesai Survei',
                'badge'   => 'success',
            ],
        ];
    }
}
